"""Add timestamps to LoanRequest

Revision ID: f9b2415edcdb
Revises: 799974bc6f6a
Create Date: 2026-01-05 05:01:24.925590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b2415edcdb'
down_revision: Union[str, None] = '799974bc6f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_requests', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('loan_requests', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_requests', 'updated_at')
    op.drop_column('loan_requests', 'created_at')
    # ### end Alembic commands ###
