"""Add DELETED to LoanStatus

Revision ID: ceca6e00c8da
Revises: f9b2415edcdb
Create Date: 2026-01-05 05:04:51.793086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceca6e00c8da'
down_revision: Union[str, None] = 'f9b2415edcdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
