"""create_initial_tables

Revision ID: 6baf6f05b4fc
Revises: 3bfbd4854249
Create Date: 2026-01-05 04:22:05.778218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6baf6f05b4fc'
down_revision: Union[str, None] = '3bfbd4854249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
