"""Initial_models

Revision ID: 7854bbb4de58
Revises: 
Create Date: 2026-01-04 17:20:22.588904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7854bbb4de58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('dba_name', sa.String(), nullable=True),
    sa.Column('industry', sa.Enum('RETAIL', 'CONSTRUCTION', 'TRANSPORTATION', 'HEALTHCARE', 'HOSPITALITY', 'MANUFACTURING', 'TECHNOLOGY', 'OTHER', name='industrytype'), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('years_in_business', sa.Float(), nullable=False),
    sa.Column('annual_revenue', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_legal_name'), 'businesses', ['legal_name'], unique=False)
    op.create_table('lenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('excluded_states', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('excluded_industries', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('excluded_equipment_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('business_credits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('paynet_score', sa.Integer(), nullable=True),
    sa.Column('has_comparable_credit', sa.Boolean(), nullable=False),
    sa.Column('comparable_credit_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('open_trade_lines_count', sa.Integer(), nullable=False),
    sa.Column('has_collections', sa.Boolean(), nullable=False),
    sa.Column('has_tax_liens', sa.Boolean(), nullable=False),
    sa.Column('collections_charge_off_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('lender_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lender_id', sa.UUID(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('tier_name', sa.String(), nullable=False),
    sa.Column('is_medical_program', sa.Boolean(), nullable=False),
    sa.Column('is_corporate_only', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lender_programs_lender_id'), 'lender_programs', ['lender_id'], unique=False)
    op.create_table('loan_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.String(), nullable=False),
    sa.Column('equipment_age_years', sa.Integer(), nullable=True),
    sa.Column('equipment_cost', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('soft_costs', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_private_party_sale', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'PROCESSING', 'COMPLETED', name='loanstatus'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loan_requests_business_id'), 'loan_requests', ['business_id'], unique=False)
    op.create_index(op.f('ix_loan_requests_status'), 'loan_requests', ['status'], unique=False)
    op.create_table('personal_guarantors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('fico_score', sa.Integer(), nullable=False),
    sa.Column('ownership_percentage', sa.Float(), nullable=False),
    sa.Column('has_bankruptcy', sa.Boolean(), nullable=False),
    sa.Column('bankruptcy_discharge_date', sa.Date(), nullable=True),
    sa.Column('has_foreclosure', sa.Boolean(), nullable=False),
    sa.Column('has_repossession', sa.Boolean(), nullable=False),
    sa.Column('has_judgement', sa.Boolean(), nullable=False),
    sa.Column('revolving_debt_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_unsecured_debt', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_guarantors_business_id'), 'personal_guarantors', ['business_id'], unique=False)
    op.create_table('lender_criteria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('criteria_type', sa.Enum('FICO_MIN', 'PAYNET_MIN', 'TIB_MIN', 'LOAN_AMOUNT_MIN', 'LOAN_AMOUNT_MAX', 'REVENUE_MIN', 'INDUSTRY_ALLOWED', 'INDUSTRY_EXCLUDED', name='criteriatype'), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['lender_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lender_criteria_program_id'), 'lender_criteria', ['program_id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('loan_request_id', sa.UUID(), nullable=False),
    sa.Column('lender_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=True),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('fit_score', sa.Integer(), nullable=False),
    sa.Column('rejection_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criteria_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lender_id'], ['lenders.id'], ),
    sa.ForeignKeyConstraint(['loan_request_id'], ['loan_requests.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['lender_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_lender_id'), 'match_results', ['lender_id'], unique=False)
    op.create_index(op.f('ix_match_results_loan_request_id'), 'match_results', ['loan_request_id'], unique=False)
    op.create_index(op.f('ix_match_results_program_id'), 'match_results', ['program_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_results_program_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_loan_request_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_lender_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_lender_criteria_program_id'), table_name='lender_criteria')
    op.drop_table('lender_criteria')
    op.drop_index(op.f('ix_personal_guarantors_business_id'), table_name='personal_guarantors')
    op.drop_table('personal_guarantors')
    op.drop_index(op.f('ix_loan_requests_status'), table_name='loan_requests')
    op.drop_index(op.f('ix_loan_requests_business_id'), table_name='loan_requests')
    op.drop_table('loan_requests')
    op.drop_index(op.f('ix_lender_programs_lender_id'), table_name='lender_programs')
    op.drop_table('lender_programs')
    op.drop_table('business_credits')
    op.drop_table('lenders')
    op.drop_index(op.f('ix_businesses_legal_name'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
